from aim_fsm import *


class AgentSmokeTest(StateMachineProgram):
    def setup(self):
        #     start: Say("agent smoke ready") =C=> idle
        #     idle: StateNode()
        #     idle =TM=> got_text
        #     idle =Hear=> got_speech
        #     got_text: Say("text event received") =C=> idle
        #     got_speech: Say("speech event received") =C=> idle
        
        # Code generated by genfsm on Wed Apr 15 17:03:30 2026:
        
        start = Say("agent smoke ready") .set_name("start") .set_parent(self)
        idle = StateNode() .set_name("idle") .set_parent(self)
        got_text = Say("text event received") .set_name("got_text") .set_parent(self)
        got_speech = Say("speech event received") .set_name("got_speech") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(idle)
        
        textmsgtrans1 = TextMsgTrans() .set_name("textmsgtrans1")
        textmsgtrans1 .add_sources(idle) .add_destinations(got_text)
        
        heartrans1 = HearTrans() .set_name("heartrans1")
        heartrans1 .add_sources(idle) .add_destinations(got_speech)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(got_text) .add_destinations(idle)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(got_speech) .add_destinations(idle)
        
        return self
