from aim_fsm import *

from asteria_demo_nodes import ApproachSpecificAprilTag


# Current default uses AprilTag-0 as the operator-marker stand-in because that is
# the most validated live AprilTag surface in this workspace today.
OPERATOR_TAG_ID = 0


class ApproachOperatorScan(StateMachineProgram):
    def setup(self):
        #     start: Say("Looking for the operator tag") =C=> approach_operator
        # 
        #     approach_operator: ApproachSpecificAprilTag(OPERATOR_TAG_ID, label="the operator tag")
        #     approach_operator =C=> done
        #     approach_operator =F=> failed
        # 
        #     done: Say("I am in operator range")
        #     failed: Print("approach_operator_scan failed")
        
        # Code generated by genfsm on Mon Apr 20 16:30:53 2026:
        
        start = Say("Looking for the operator tag") .set_name("start") .set_parent(self)
        approach_operator = ApproachSpecificAprilTag(OPERATOR_TAG_ID, label="the operator tag") .set_name("approach_operator") .set_parent(self)
        done = Say("I am in operator range") .set_name("done") .set_parent(self)
        failed = Print("approach_operator_scan failed") .set_name("failed") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(approach_operator)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(approach_operator) .add_destinations(done)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(approach_operator) .add_destinations(failed)
        
        return self
