from aim_fsm import *


class AsteriaStarDance(StateMachineProgram):
    # A compact performance FSM that draws a star-like path with a dramatic intro and finale.
    # Uses only Say, Forward, and Turn primitives that are already validated in this workspace.
    def setup(self):
        #     start: Say("Initiating Asteria star dance")
        #         =C=> Turn(36)
        #         =C=> Forward(180)
        #         =C=> Turn(144)
        #         =C=> Forward(180)
        #         =C=> Turn(144)
        #         =C=> Forward(180)
        #         =C=> Turn(144)
        #         =C=> Forward(180)
        #         =C=> Turn(144)
        #         =C=> Forward(180)
        #         =C=> Say("Star traced")
        #         =C=> Turn(120)
        #         =C=> Turn(120)
        #         =C=> Turn(120)
        #         =C=> Say("Finale")
        #         =C=> Turn(180)
        #         =C=> Turn(180)
        #         =C=> Say("Asteria star dance complete")
        
        # Code generated by genfsm on Wed Apr 15 17:03:25 2026:
        
        start = Say("Initiating Asteria star dance") .set_name("start") .set_parent(self)
        turn1 = Turn(36) .set_name("turn1") .set_parent(self)
        forward1 = Forward(180) .set_name("forward1") .set_parent(self)
        turn2 = Turn(144) .set_name("turn2") .set_parent(self)
        forward2 = Forward(180) .set_name("forward2") .set_parent(self)
        turn3 = Turn(144) .set_name("turn3") .set_parent(self)
        forward3 = Forward(180) .set_name("forward3") .set_parent(self)
        turn4 = Turn(144) .set_name("turn4") .set_parent(self)
        forward4 = Forward(180) .set_name("forward4") .set_parent(self)
        turn5 = Turn(144) .set_name("turn5") .set_parent(self)
        forward5 = Forward(180) .set_name("forward5") .set_parent(self)
        say1 = Say("Star traced") .set_name("say1") .set_parent(self)
        turn6 = Turn(120) .set_name("turn6") .set_parent(self)
        turn7 = Turn(120) .set_name("turn7") .set_parent(self)
        turn8 = Turn(120) .set_name("turn8") .set_parent(self)
        say2 = Say("Finale") .set_name("say2") .set_parent(self)
        turn9 = Turn(180) .set_name("turn9") .set_parent(self)
        turn10 = Turn(180) .set_name("turn10") .set_parent(self)
        say3 = Say("Asteria star dance complete") .set_name("say3") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(turn1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(turn1) .add_destinations(forward1)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(forward1) .add_destinations(turn2)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(turn2) .add_destinations(forward2)
        
        completiontrans5 = CompletionTrans() .set_name("completiontrans5")
        completiontrans5 .add_sources(forward2) .add_destinations(turn3)
        
        completiontrans6 = CompletionTrans() .set_name("completiontrans6")
        completiontrans6 .add_sources(turn3) .add_destinations(forward3)
        
        completiontrans7 = CompletionTrans() .set_name("completiontrans7")
        completiontrans7 .add_sources(forward3) .add_destinations(turn4)
        
        completiontrans8 = CompletionTrans() .set_name("completiontrans8")
        completiontrans8 .add_sources(turn4) .add_destinations(forward4)
        
        completiontrans9 = CompletionTrans() .set_name("completiontrans9")
        completiontrans9 .add_sources(forward4) .add_destinations(turn5)
        
        completiontrans10 = CompletionTrans() .set_name("completiontrans10")
        completiontrans10 .add_sources(turn5) .add_destinations(forward5)
        
        completiontrans11 = CompletionTrans() .set_name("completiontrans11")
        completiontrans11 .add_sources(forward5) .add_destinations(say1)
        
        completiontrans12 = CompletionTrans() .set_name("completiontrans12")
        completiontrans12 .add_sources(say1) .add_destinations(turn6)
        
        completiontrans13 = CompletionTrans() .set_name("completiontrans13")
        completiontrans13 .add_sources(turn6) .add_destinations(turn7)
        
        completiontrans14 = CompletionTrans() .set_name("completiontrans14")
        completiontrans14 .add_sources(turn7) .add_destinations(turn8)
        
        completiontrans15 = CompletionTrans() .set_name("completiontrans15")
        completiontrans15 .add_sources(turn8) .add_destinations(say2)
        
        completiontrans16 = CompletionTrans() .set_name("completiontrans16")
        completiontrans16 .add_sources(say2) .add_destinations(turn9)
        
        completiontrans17 = CompletionTrans() .set_name("completiontrans17")
        completiontrans17 .add_sources(turn9) .add_destinations(turn10)
        
        completiontrans18 = CompletionTrans() .set_name("completiontrans18")
        completiontrans18 .add_sources(turn10) .add_destinations(say3)
        
        return self
