from aim_fsm import *


class AsteriaDemo(StateMachineProgram):
 def setup(self):
     #  Say("asteria_demo ready") =C=> Forward(10) =C=> Turn(10) =C=> Say("asteria_demo complete")
     
     # Code generated by genfsm on Wed Apr 15 17:03:28 2026:
     
     say1 = Say("asteria_demo ready") .set_name("say1") .set_parent(self)
     forward1 = Forward(10) .set_name("forward1") .set_parent(self)
     turn1 = Turn(10) .set_name("turn1") .set_parent(self)
     say2 = Say("asteria_demo complete") .set_name("say2") .set_parent(self)
     
     completiontrans1 = CompletionTrans() .set_name("completiontrans1")
     completiontrans1 .add_sources(say1) .add_destinations(forward1)
     
     completiontrans2 = CompletionTrans() .set_name("completiontrans2")
     completiontrans2 .add_sources(forward1) .add_destinations(turn1)
     
     completiontrans3 = CompletionTrans() .set_name("completiontrans3")
     completiontrans3 .add_sources(turn1) .add_destinations(say2)
     
     return self
