from aim_fsm import *


class Circle10cm(StateMachineProgram):
    # Approximates a 10 cm radius circle with a 12-sided polygon.
    # Chord length ~= 2 * r * sin(pi / 12) = 51.8 mm, rounded to 52 mm.
    def setup(self):
        #     start: Say("circle_10cm ready") =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Forward(52) =C=> Turn(30) =C=> Say("circle_10cm complete")
        
        # Code generated by genfsm on Wed Apr 15 17:02:54 2026:
        
        start = Say("circle_10cm ready") .set_name("start") .set_parent(self)
        forward1 = Forward(52) .set_name("forward1") .set_parent(self)
        turn1 = Turn(30) .set_name("turn1") .set_parent(self)
        forward2 = Forward(52) .set_name("forward2") .set_parent(self)
        turn2 = Turn(30) .set_name("turn2") .set_parent(self)
        forward3 = Forward(52) .set_name("forward3") .set_parent(self)
        turn3 = Turn(30) .set_name("turn3") .set_parent(self)
        forward4 = Forward(52) .set_name("forward4") .set_parent(self)
        turn4 = Turn(30) .set_name("turn4") .set_parent(self)
        forward5 = Forward(52) .set_name("forward5") .set_parent(self)
        turn5 = Turn(30) .set_name("turn5") .set_parent(self)
        forward6 = Forward(52) .set_name("forward6") .set_parent(self)
        turn6 = Turn(30) .set_name("turn6") .set_parent(self)
        forward7 = Forward(52) .set_name("forward7") .set_parent(self)
        turn7 = Turn(30) .set_name("turn7") .set_parent(self)
        forward8 = Forward(52) .set_name("forward8") .set_parent(self)
        turn8 = Turn(30) .set_name("turn8") .set_parent(self)
        forward9 = Forward(52) .set_name("forward9") .set_parent(self)
        turn9 = Turn(30) .set_name("turn9") .set_parent(self)
        forward10 = Forward(52) .set_name("forward10") .set_parent(self)
        turn10 = Turn(30) .set_name("turn10") .set_parent(self)
        forward11 = Forward(52) .set_name("forward11") .set_parent(self)
        turn11 = Turn(30) .set_name("turn11") .set_parent(self)
        forward12 = Forward(52) .set_name("forward12") .set_parent(self)
        turn12 = Turn(30) .set_name("turn12") .set_parent(self)
        say1 = Say("circle_10cm complete") .set_name("say1") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(forward1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(forward1) .add_destinations(turn1)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(turn1) .add_destinations(forward2)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(forward2) .add_destinations(turn2)
        
        completiontrans5 = CompletionTrans() .set_name("completiontrans5")
        completiontrans5 .add_sources(turn2) .add_destinations(forward3)
        
        completiontrans6 = CompletionTrans() .set_name("completiontrans6")
        completiontrans6 .add_sources(forward3) .add_destinations(turn3)
        
        completiontrans7 = CompletionTrans() .set_name("completiontrans7")
        completiontrans7 .add_sources(turn3) .add_destinations(forward4)
        
        completiontrans8 = CompletionTrans() .set_name("completiontrans8")
        completiontrans8 .add_sources(forward4) .add_destinations(turn4)
        
        completiontrans9 = CompletionTrans() .set_name("completiontrans9")
        completiontrans9 .add_sources(turn4) .add_destinations(forward5)
        
        completiontrans10 = CompletionTrans() .set_name("completiontrans10")
        completiontrans10 .add_sources(forward5) .add_destinations(turn5)
        
        completiontrans11 = CompletionTrans() .set_name("completiontrans11")
        completiontrans11 .add_sources(turn5) .add_destinations(forward6)
        
        completiontrans12 = CompletionTrans() .set_name("completiontrans12")
        completiontrans12 .add_sources(forward6) .add_destinations(turn6)
        
        completiontrans13 = CompletionTrans() .set_name("completiontrans13")
        completiontrans13 .add_sources(turn6) .add_destinations(forward7)
        
        completiontrans14 = CompletionTrans() .set_name("completiontrans14")
        completiontrans14 .add_sources(forward7) .add_destinations(turn7)
        
        completiontrans15 = CompletionTrans() .set_name("completiontrans15")
        completiontrans15 .add_sources(turn7) .add_destinations(forward8)
        
        completiontrans16 = CompletionTrans() .set_name("completiontrans16")
        completiontrans16 .add_sources(forward8) .add_destinations(turn8)
        
        completiontrans17 = CompletionTrans() .set_name("completiontrans17")
        completiontrans17 .add_sources(turn8) .add_destinations(forward9)
        
        completiontrans18 = CompletionTrans() .set_name("completiontrans18")
        completiontrans18 .add_sources(forward9) .add_destinations(turn9)
        
        completiontrans19 = CompletionTrans() .set_name("completiontrans19")
        completiontrans19 .add_sources(turn9) .add_destinations(forward10)
        
        completiontrans20 = CompletionTrans() .set_name("completiontrans20")
        completiontrans20 .add_sources(forward10) .add_destinations(turn10)
        
        completiontrans21 = CompletionTrans() .set_name("completiontrans21")
        completiontrans21 .add_sources(turn10) .add_destinations(forward11)
        
        completiontrans22 = CompletionTrans() .set_name("completiontrans22")
        completiontrans22 .add_sources(forward11) .add_destinations(turn11)
        
        completiontrans23 = CompletionTrans() .set_name("completiontrans23")
        completiontrans23 .add_sources(turn11) .add_destinations(forward12)
        
        completiontrans24 = CompletionTrans() .set_name("completiontrans24")
        completiontrans24 .add_sources(forward12) .add_destinations(turn12)
        
        completiontrans25 = CompletionTrans() .set_name("completiontrans25")
        completiontrans25 .add_sources(turn12) .add_destinations(say1)
        
        return self
