from aim_fsm import *
import json
from pathlib import Path

from approach_operator_scan import ApproachOperatorScan
from scene_inventory_scan import SceneInventoryScan


def _format_list_phrase(values, fallback):
    cleaned = [str(value) for value in values if value]
    if not cleaned:
        return fallback
    if len(cleaned) == 1:
        return cleaned[0]
    if len(cleaned) == 2:
        return f"{cleaned[0]} and {cleaned[1]}"
    return f"{cleaned[0]}, {cleaned[1]}, and {cleaned[2]}"


class DeskMissionDemo(StateMachineProgram):
    class SayLatestInventorySummary(ActionNode):
        def __init__(self):
            super().__init__()
            self.utterance = ""

        def start(self, event=None):
            super().start(event)
            manifest_path = (
                Path(__file__).resolve().parents[1]
                / "images"
                / "scene_inventory_scan"
                / "latest_scene_inventory_scan.json"
            )
            utterance = "I finished the scan, but I could not read back the inventory."
            try:
                manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
                aggregate = manifest.get("aggregate", {})
                world_names = list(aggregate.get("world_visible_names", []))
                tag_ids = [f"tag {tag_id}" for tag_id in aggregate.get("ai_tag_ids", [])[:3]]
                cargo_classes = list(aggregate.get("ai_cargo_classes", [])[:3])

                world_clause = (
                    f"I saw {len(world_names)} mapped objects"
                    if world_names
                    else "I saw no mapped objects"
                )
                tag_clause = f"visible tags were {_format_list_phrase(tag_ids, 'none')}"
                cargo_clause = f"cargo looked like {_format_list_phrase(cargo_classes, 'nothing obvious')}"
                utterance = f"{world_clause}. {tag_clause}. {cargo_clause}."
                print(f"desk mission summary from {manifest_path}: {utterance}")
            except Exception as exc:
                print(f"desk mission summary unavailable from {manifest_path}: {exc}")

            self.utterance = utterance
            if utterance.strip() == "":
                self.post_completion()
                return
            self.robot.actuators["sound"].say_text(self, utterance)

    def setup(self):
        #     start: Say("Starting desk mission demo") =C=> scan
        # 
        #     scan: SceneInventoryScan()
        #     scan =C=> summarize
        #     scan =F=> failed
        # 
        #     summarize: self.SayLatestInventorySummary()
        #     summarize =C=> approach_operator
        #     summarize =F=> failed
        # 
        #     approach_operator: ApproachOperatorScan()
        #     approach_operator =C=> done
        #     approach_operator =F=> failed
        # 
        #     done: Say("Desk mission demo complete")
        #     failed: Say("Desk mission demo failed")
        
        # Code generated by genfsm on Mon Apr 20 16:41:12 2026:
        
        start = Say("Starting desk mission demo") .set_name("start") .set_parent(self)
        scan = SceneInventoryScan() .set_name("scan") .set_parent(self)
        summarize = self.SayLatestInventorySummary() .set_name("summarize") .set_parent(self)
        approach_operator = ApproachOperatorScan() .set_name("approach_operator") .set_parent(self)
        done = Say("Desk mission demo complete") .set_name("done") .set_parent(self)
        failed = Say("Desk mission demo failed") .set_name("failed") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(scan)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(scan) .add_destinations(summarize)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(scan) .add_destinations(failed)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(summarize) .add_destinations(approach_operator)
        
        failuretrans2 = FailureTrans() .set_name("failuretrans2")
        failuretrans2 .add_sources(summarize) .add_destinations(failed)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(approach_operator) .add_destinations(done)
        
        failuretrans3 = FailureTrans() .set_name("failuretrans3")
        failuretrans3 .add_sources(approach_operator) .add_destinations(failed)
        
        return self
