from aim_fsm import *

from asteria_demo_nodes import FollowAnyAprilTag


class FollowMeTag(StateMachineProgram):
    def setup(self):
        #     start: Say("Starting follow me tag") =C=> follow_tag
        # 
        #     follow_tag: FollowAnyAprilTag()
        #     follow_tag =F=> failed
        # 
        #     failed: Print("follow_me_tag failed")
        
        # Code generated by genfsm on Fri Apr 17 16:38:52 2026:
        
        start = Say("Starting follow me tag") .set_name("start") .set_parent(self)
        follow_tag = FollowAnyAprilTag() .set_name("follow_tag") .set_parent(self)
        failed = Print("follow_me_tag failed") .set_name("failed") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(follow_tag)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(follow_tag) .add_destinations(failed)
        
        return self
