from aim_fsm import *

from asteria_demo_nodes import ChargeAndKickBarrel


class GetMad(StateMachineProgram):
    def setup(self):
        #     start: Say("I am getting mad") =C=> get_mad
        # 
        #     get_mad: ChargeAndKickBarrel()
        #     get_mad =C=> done
        #     get_mad =F=> failed
        # 
        #     done: Say("I feel better now")
        #     failed: Print("get_mad failed")
        
        # Code generated by genfsm on Fri Apr 17 16:44:04 2026:
        
        start = Say("I am getting mad") .set_name("start") .set_parent(self)
        get_mad = ChargeAndKickBarrel() .set_name("get_mad") .set_parent(self)
        done = Say("I feel better now") .set_name("done") .set_parent(self)
        failed = Print("get_mad failed") .set_name("failed") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(get_mad)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(get_mad) .add_destinations(done)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(get_mad) .add_destinations(failed)
        
        return self
