from aim_fsm import *


class July4Celebration(StateMachineProgram):
    # A celebratory routine with spoken cues, a star-like path, and a red/white/blue LED finale.
    # Intended as a creative example file; create/compile is safe offline, but running it is motionful.
    def setup(self):
        #     start: Say("Happy Fourth of July from Asteria")
        #         =C=> Flash([
        #             (vex.Color.RED, 0.18),
        #             (vex.Color.WHITE, 0.18),
        #             (vex.Color.BLUE, 0.18),
        #             (vex.Color.TRANSPARENT, 0.10)
        #         ], num_cycles=3)
        #         =C=> Say("Drawing a star")
        #         =C=> Turn(36)
        #         =C=> Forward(140)
        #         =C=> Turn(144)
        #         =C=> Forward(140)
        #         =C=> Turn(144)
        #         =C=> Forward(140)
        #         =C=> Turn(144)
        #         =C=> Forward(140)
        #         =C=> Turn(144)
        #         =C=> Forward(140)
        #         =C=> Say("Fireworks finale")
        #         =C=> Flash([
        #             ((vex.Color.RED, vex.Color.WHITE, vex.Color.BLUE, vex.Color.RED, vex.Color.WHITE, vex.Color.BLUE), 0.12),
        #             ((vex.Color.BLUE, vex.Color.RED, vex.Color.WHITE, vex.Color.BLUE, vex.Color.RED, vex.Color.WHITE), 0.12),
        #             ((vex.Color.WHITE, vex.Color.BLUE, vex.Color.RED, vex.Color.WHITE, vex.Color.BLUE, vex.Color.RED), 0.12),
        #             (vex.Color.TRANSPARENT, 0.08)
        #         ], num_cycles=5)
        #         =C=> Turn(120)
        #         =C=> Turn(120)
        #         =C=> Turn(120)
        #         =C=> Say("July Fourth celebration complete")
        
        # Code generated by genfsm on Thu Apr 16 20:44:38 2026:
        
        start = Say("Happy Fourth of July from Asteria") .set_name("start") .set_parent(self)
        flash1 = Flash([
            (vex.Color.RED, 0.18),
            (vex.Color.WHITE, 0.18),
            (vex.Color.BLUE, 0.18),
            (vex.Color.TRANSPARENT, 0.10)
        ], num_cycles=3) .set_name("flash1") .set_parent(self)
        say1 = Say("Drawing a star") .set_name("say1") .set_parent(self)
        turn1 = Turn(36) .set_name("turn1") .set_parent(self)
        forward1 = Forward(140) .set_name("forward1") .set_parent(self)
        turn2 = Turn(144) .set_name("turn2") .set_parent(self)
        forward2 = Forward(140) .set_name("forward2") .set_parent(self)
        turn3 = Turn(144) .set_name("turn3") .set_parent(self)
        forward3 = Forward(140) .set_name("forward3") .set_parent(self)
        turn4 = Turn(144) .set_name("turn4") .set_parent(self)
        forward4 = Forward(140) .set_name("forward4") .set_parent(self)
        turn5 = Turn(144) .set_name("turn5") .set_parent(self)
        forward5 = Forward(140) .set_name("forward5") .set_parent(self)
        say2 = Say("Fireworks finale") .set_name("say2") .set_parent(self)
        flash2 = Flash([
            ((vex.Color.RED, vex.Color.WHITE, vex.Color.BLUE, vex.Color.RED, vex.Color.WHITE, vex.Color.BLUE), 0.12),
            ((vex.Color.BLUE, vex.Color.RED, vex.Color.WHITE, vex.Color.BLUE, vex.Color.RED, vex.Color.WHITE), 0.12),
            ((vex.Color.WHITE, vex.Color.BLUE, vex.Color.RED, vex.Color.WHITE, vex.Color.BLUE, vex.Color.RED), 0.12),
            (vex.Color.TRANSPARENT, 0.08)
        ], num_cycles=5) .set_name("flash2") .set_parent(self)
        turn6 = Turn(120) .set_name("turn6") .set_parent(self)
        turn7 = Turn(120) .set_name("turn7") .set_parent(self)
        turn8 = Turn(120) .set_name("turn8") .set_parent(self)
        say3 = Say("July Fourth celebration complete") .set_name("say3") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(flash1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(flash1) .add_destinations(say1)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(say1) .add_destinations(turn1)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(turn1) .add_destinations(forward1)
        
        completiontrans5 = CompletionTrans() .set_name("completiontrans5")
        completiontrans5 .add_sources(forward1) .add_destinations(turn2)
        
        completiontrans6 = CompletionTrans() .set_name("completiontrans6")
        completiontrans6 .add_sources(turn2) .add_destinations(forward2)
        
        completiontrans7 = CompletionTrans() .set_name("completiontrans7")
        completiontrans7 .add_sources(forward2) .add_destinations(turn3)
        
        completiontrans8 = CompletionTrans() .set_name("completiontrans8")
        completiontrans8 .add_sources(turn3) .add_destinations(forward3)
        
        completiontrans9 = CompletionTrans() .set_name("completiontrans9")
        completiontrans9 .add_sources(forward3) .add_destinations(turn4)
        
        completiontrans10 = CompletionTrans() .set_name("completiontrans10")
        completiontrans10 .add_sources(turn4) .add_destinations(forward4)
        
        completiontrans11 = CompletionTrans() .set_name("completiontrans11")
        completiontrans11 .add_sources(forward4) .add_destinations(turn5)
        
        completiontrans12 = CompletionTrans() .set_name("completiontrans12")
        completiontrans12 .add_sources(turn5) .add_destinations(forward5)
        
        completiontrans13 = CompletionTrans() .set_name("completiontrans13")
        completiontrans13 .add_sources(forward5) .add_destinations(say2)
        
        completiontrans14 = CompletionTrans() .set_name("completiontrans14")
        completiontrans14 .add_sources(say2) .add_destinations(flash2)
        
        completiontrans15 = CompletionTrans() .set_name("completiontrans15")
        completiontrans15 .add_sources(flash2) .add_destinations(turn6)
        
        completiontrans16 = CompletionTrans() .set_name("completiontrans16")
        completiontrans16 .add_sources(turn6) .add_destinations(turn7)
        
        completiontrans17 = CompletionTrans() .set_name("completiontrans17")
        completiontrans17 .add_sources(turn7) .add_destinations(turn8)
        
        completiontrans18 = CompletionTrans() .set_name("completiontrans18")
        completiontrans18 .add_sources(turn8) .add_destinations(say3)
        
        return self
