from aim_fsm import *


class OpenclawProbe(StateMachineProgram):
    def setup(self):
        #     Say("openclaw_probe ready") =C=> Forward(12) =C=> Turn(9) =C=> Say("openclaw_probe complete")
        
        # Code generated by genfsm on Tue Apr 14 01:11:18 2026:
        
        say1 = Say("openclaw_probe ready") .set_name("say1") .set_parent(self)
        forward1 = Forward(12) .set_name("forward1") .set_parent(self)
        turn1 = Turn(9) .set_name("turn1") .set_parent(self)
        say2 = Say("openclaw_probe complete") .set_name("say2") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(say1) .add_destinations(forward1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(forward1) .add_destinations(turn1)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(turn1) .add_destinations(say2)
        
        return self
