from aim_fsm import *
from soccer_search_nodes import ShootHeldBallAtTag0


class SoccerTag0Shot(StateMachineProgram):
    def setup(self):
        #     start: Say("Starting soccer tag zero shot") =C=> shoot_ball
        # 
        #     shoot_ball: ShootHeldBallAtTag0()
        #     shoot_ball =C=> done
        #     shoot_ball =F=> failed
        # 
        #     done: Say("Soccer shot complete")
        #     failed: Print("soccer_tag0_shot failed")
        
        # Code generated by genfsm on Thu Apr 16 21:31:53 2026:
        
        start = Say("Starting soccer tag zero shot") .set_name("start") .set_parent(self)
        shoot_ball = ShootHeldBallAtTag0() .set_name("shoot_ball") .set_parent(self)
        done = Say("Soccer shot complete") .set_name("done") .set_parent(self)
        failed = Print("soccer_tag0_shot failed") .set_name("failed") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(shoot_ball)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(shoot_ball) .add_destinations(done)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(shoot_ball) .add_destinations(failed)
        
        return self
