from aim_fsm import *

from soccer_search_nodes import AcquireSoccerBall


class SoccerBallPickup(StateMachineProgram):
    def setup(self):
        #     start: Say("Starting soccer ball pickup") =C=> acquire_ball
        # 
        #     acquire_ball: AcquireSoccerBall()
        #     acquire_ball =C=> done
        #     acquire_ball =F=> failed
        # 
        #     done: Say("Soccer ball acquired")
        #     failed: Print("soccer_ball_pickup failed")
        
        # Code generated by genfsm on Thu Apr 16 21:15:05 2026:
        
        start = Say("Starting soccer ball pickup") .set_name("start") .set_parent(self)
        acquire_ball = AcquireSoccerBall() .set_name("acquire_ball") .set_parent(self)
        done = Say("Soccer ball acquired") .set_name("done") .set_parent(self)
        failed = Print("soccer_ball_pickup failed") .set_name("failed") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(acquire_ball)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(acquire_ball) .add_destinations(done)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(acquire_ball) .add_destinations(failed)
        
        return self
