from aim_fsm import *

from soccer_search_nodes import AcquireSoccerBall, ShootHeldBallAtTag0


class SoccerBowlingRound(StateMachineProgram):
    def setup(self):
        #     start: Say("Starting bowling round") =C=> acquire_ball
        # 
        #     acquire_ball: AcquireSoccerBall()
        #     acquire_ball =C=> announce_shot
        #     acquire_ball =F=> failed
        # 
        #     announce_shot: Say("Ball acquired. Looking for AprilTag 0") =C=> take_shot
        # 
        #     take_shot: ShootHeldBallAtTag0()
        #     take_shot =C=> done
        #     take_shot =F=> failed
        # 
        #     done: Say("Bowling round complete")
        #     failed: Print("soccer_bowling_round failed")
        
        # Code generated by genfsm on Fri Apr 17 15:37:33 2026:
        
        start = Say("Starting bowling round") .set_name("start") .set_parent(self)
        acquire_ball = AcquireSoccerBall() .set_name("acquire_ball") .set_parent(self)
        announce_shot = Say("Ball acquired. Looking for AprilTag 0") .set_name("announce_shot") .set_parent(self)
        take_shot = ShootHeldBallAtTag0() .set_name("take_shot") .set_parent(self)
        done = Say("Bowling round complete") .set_name("done") .set_parent(self)
        failed = Print("soccer_bowling_round failed") .set_name("failed") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(acquire_ball)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(acquire_ball) .add_destinations(announce_shot)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(acquire_ball) .add_destinations(failed)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(announce_shot) .add_destinations(take_shot)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(take_shot) .add_destinations(done)
        
        failuretrans2 = FailureTrans() .set_name("failuretrans2")
        failuretrans2 .add_sources(take_shot) .add_destinations(failed)
        
        return self
