from aim_fsm import *

from asteria_demo_nodes import GalleryStop


class TagGalleryTour(StateMachineProgram):
    def setup(self):
        #     start: Say("Starting tag gallery tour") =C=> tag_zero
        # 
        #     tag_zero: GalleryStop(0) =C=> tag_one
        #     tag_one: GalleryStop(1) =C=> tag_two
        #     tag_two: GalleryStop(2) =C=> tag_three
        #     tag_three: GalleryStop(3) =C=> tag_four
        #     tag_four: GalleryStop(4) =C=> done
        # 
        #     done: Say("Tag gallery tour complete")
        
        # Code generated by genfsm on Fri Apr 17 16:41:57 2026:
        
        start = Say("Starting tag gallery tour") .set_name("start") .set_parent(self)
        tag_zero = GalleryStop(0) .set_name("tag_zero") .set_parent(self)
        tag_one = GalleryStop(1) .set_name("tag_one") .set_parent(self)
        tag_two = GalleryStop(2) .set_name("tag_two") .set_parent(self)
        tag_three = GalleryStop(3) .set_name("tag_three") .set_parent(self)
        tag_four = GalleryStop(4) .set_name("tag_four") .set_parent(self)
        done = Say("Tag gallery tour complete") .set_name("done") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(tag_zero)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(tag_zero) .add_destinations(tag_one)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(tag_one) .add_destinations(tag_two)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(tag_two) .add_destinations(tag_three)
        
        completiontrans5 = CompletionTrans() .set_name("completiontrans5")
        completiontrans5 .add_sources(tag_three) .add_destinations(tag_four)
        
        completiontrans6 = CompletionTrans() .set_name("completiontrans6")
        completiontrans6 .add_sources(tag_four) .add_destinations(done)
        
        return self
