from aim_fsm import *


class TestAgentFlow(StateMachineProgram):
    def setup(self):
        #     Say("test_agent_flow ready") =C=> Forward(120) =C=> Turn(90) =C=> Say("test_agent_flow complete")
        
        # Code generated by genfsm on Tue Apr 14 09:52:47 2026:
        
        say1 = Say("test_agent_flow ready") .set_name("say1") .set_parent(self)
        forward1 = Forward(120) .set_name("forward1") .set_parent(self)
        turn1 = Turn(90) .set_name("turn1") .set_parent(self)
        say2 = Say("test_agent_flow complete") .set_name("say2") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(say1) .add_destinations(forward1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(forward1) .add_destinations(turn1)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(turn1) .add_destinations(say2)
        
        return self
