from aim_fsm import *


class Zigzag20s(StateMachineProgram):
    # Approximate 20-second zigzag. Actual runtime depends on drivetrain speed,
    # floor traction, and the current AIM runtime timing.
    def setup(self):
        #     start: Say("Starting zigzag run")
        #         =C=> Forward(160)
        #         =C=> Turn(28)
        #         =C=> Forward(160)
        #         =C=> Turn(-56)
        #         =C=> Forward(160)
        #         =C=> Turn(56)
        #         =C=> Forward(160)
        #         =C=> Turn(-56)
        #         =C=> Forward(160)
        #         =C=> Turn(56)
        #         =C=> Forward(160)
        #         =C=> Turn(-56)
        #         =C=> Forward(160)
        #         =C=> Turn(28)
        #         =C=> Say("I'm done now")
        
        # Code generated by genfsm on Wed Apr 15 19:38:09 2026:
        
        start = Say("Starting zigzag run") .set_name("start") .set_parent(self)
        forward1 = Forward(160) .set_name("forward1") .set_parent(self)
        turn1 = Turn(28) .set_name("turn1") .set_parent(self)
        forward2 = Forward(160) .set_name("forward2") .set_parent(self)
        turn2 = Turn(-56) .set_name("turn2") .set_parent(self)
        forward3 = Forward(160) .set_name("forward3") .set_parent(self)
        turn3 = Turn(56) .set_name("turn3") .set_parent(self)
        forward4 = Forward(160) .set_name("forward4") .set_parent(self)
        turn4 = Turn(-56) .set_name("turn4") .set_parent(self)
        forward5 = Forward(160) .set_name("forward5") .set_parent(self)
        turn5 = Turn(56) .set_name("turn5") .set_parent(self)
        forward6 = Forward(160) .set_name("forward6") .set_parent(self)
        turn6 = Turn(-56) .set_name("turn6") .set_parent(self)
        forward7 = Forward(160) .set_name("forward7") .set_parent(self)
        turn7 = Turn(28) .set_name("turn7") .set_parent(self)
        say1 = Say("I'm done now") .set_name("say1") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start) .add_destinations(forward1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(forward1) .add_destinations(turn1)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(turn1) .add_destinations(forward2)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(forward2) .add_destinations(turn2)
        
        completiontrans5 = CompletionTrans() .set_name("completiontrans5")
        completiontrans5 .add_sources(turn2) .add_destinations(forward3)
        
        completiontrans6 = CompletionTrans() .set_name("completiontrans6")
        completiontrans6 .add_sources(forward3) .add_destinations(turn3)
        
        completiontrans7 = CompletionTrans() .set_name("completiontrans7")
        completiontrans7 .add_sources(turn3) .add_destinations(forward4)
        
        completiontrans8 = CompletionTrans() .set_name("completiontrans8")
        completiontrans8 .add_sources(forward4) .add_destinations(turn4)
        
        completiontrans9 = CompletionTrans() .set_name("completiontrans9")
        completiontrans9 .add_sources(turn4) .add_destinations(forward5)
        
        completiontrans10 = CompletionTrans() .set_name("completiontrans10")
        completiontrans10 .add_sources(forward5) .add_destinations(turn5)
        
        completiontrans11 = CompletionTrans() .set_name("completiontrans11")
        completiontrans11 .add_sources(turn5) .add_destinations(forward6)
        
        completiontrans12 = CompletionTrans() .set_name("completiontrans12")
        completiontrans12 .add_sources(forward6) .add_destinations(turn6)
        
        completiontrans13 = CompletionTrans() .set_name("completiontrans13")
        completiontrans13 .add_sources(turn6) .add_destinations(forward7)
        
        completiontrans14 = CompletionTrans() .set_name("completiontrans14")
        completiontrans14 .add_sources(forward7) .add_destinations(turn7)
        
        completiontrans15 = CompletionTrans() .set_name("completiontrans15")
        completiontrans15 .add_sources(turn7) .add_destinations(say1)
        
        return self
